server:
  servlet:
    context-path: /mybatis
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost/mybatis
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
